services:
  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: metabase
  #   hostname: metabase
  #   volumes:
  #     - /dev/urandom:/dev/random:ro
  #   ports:
  #     - 3000:3000
  #   environment:
  #     MB_DB_TYPE: postgres
  #     MB_DB_DBNAME: noah
  #     MB_DB_PORT: 5432
  #     MB_DB_USER: admin
  #     MB_DB_PASS: example
  #     MB_DB_HOST: db
  #   networks:
  #     - datanet
  #   healthcheck:
  #     test: curl --fail -I http://localhost:3000/api/health || exit 1
  #     interval: 15s
  #     timeout: 5s
  #     retries: 5
  #   depends_on: 
  #     - db

  # mb-user-creation:
  #   build: 
  #     dockerfile: Dockerfile-mb-user-creation
  #     context: ./metabase
  #   command: >
  #    bash -c "MB_HOSTNAME=metabase MB_PORT=3000 /app/create_users.sh"
  #   networks:
  #     - datanet
  #   depends_on: 
  #     metabase:
  #       condition: service_healthy
  #       restart: true

  db:
    image: postgres:16.0-alpine3.17
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: noah
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - datanet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - datanet

networks:
  datanet:
    driver: bridge